# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/connection_pool/all/connection_pool.rbi
#
# connection_pool-3.0.2

class ConnectionPool
  def available; end
  def checkin(force: nil); end
  def checkout(timeout: nil, **); end
  def discard_current_connection(&block); end
  def idle; end
  def initialize(timeout: nil, size: nil, auto_reload_after_fork: nil, name: nil, &); end
  def reap(idle_seconds: nil, &); end
  def reload(&); end
  def self.after_fork; end
  def self.wrap(**, &); end
  def shutdown(&); end
  def size; end
  def then(**); end
  def with(**); end
end
class ConnectionPool::TimedStack
  def <<(obj, **); end
  def connection_stored?(**); end
  def current_time; end
  def decrement_created; end
  def empty?; end
  def fetch_connection(**); end
  def idle; end
  def idle_connections?(idle_seconds); end
  def initialize(size: nil, &block); end
  def length; end
  def max; end
  def pop(timeout: nil, exception: nil, **); end
  def push(obj, **); end
  def reap(idle_seconds:); end
  def reserve_idle_connection(idle_seconds); end
  def shutdown(reload: nil, &block); end
  def shutdown_connections(**); end
  def store_connection(obj, **); end
  def try_create(**); end
  def try_fetch_connection(**); end
end
class ConnectionPool::Wrapper < BasicObject
  def initialize(**options, &); end
  def method_missing(name, *, **, &); end
  def pool_available; end
  def pool_shutdown(&); end
  def pool_size; end
  def respond_to?(id, *, **); end
  def respond_to_missing?(id, *, **); end
  def with(**, &); end
  def wrapped_pool; end
end
module ConnectionPool::ForkTracker
  def _fork; end
end
class ConnectionPool::Error < RuntimeError
end
class ConnectionPool::PoolShuttingDownError < ConnectionPool::Error
end
class ConnectionPool::TimeoutError < Timeout::Error
end
