# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/timeout/all/timeout.rbi
#
# timeout-0.5.0

module Timeout
  def self.timeout(sec, klass = nil, message = nil, &block); end
  def timeout(*args, &block); end
end
class Timeout::ExitException < Exception
  def exception(*); end
end
class Timeout::Error < RuntimeError
  def self.handle_timeout(message); end
end
class Timeout::State
  def condvar; end
  def create_timeout_thread; end
  def ensure_timeout_thread_created; end
  def initialize; end
  def queue; end
  def queue_mutex; end
  def self.instance; end
end
class Timeout::Request
  def deadline; end
  def done?; end
  def expired?(now); end
  def finished; end
  def initialize(thread, timeout, exception_class, message); end
  def interrupt; end
end
